# Generated by Django 6.0.3 on 2026-04-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20, verbose_name='Status do agendamento'),
        ),
    ]
