# Generated by Django 4.2.29 on 2026-04-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0003_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
